name: international_phone_text_field
description: A Flutter package for international phone field with country code.
homepage: https://github.com/iamtechieboy/international_phone_text_field
version: 0.0.1+5

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'


dependencies:

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.9.0
  formz: ^0.7.0

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flag/
    - assets/flag/AD.png
    - assets/flag/AE.png
    - assets/flag/AF.png
    - assets/flag/AG.png
    - assets/flag/AI.png
    - assets/flag/AL.png
    - assets/flag/AM.png
    - assets/flag/AO.png
    - assets/flag/AQ.png
    - assets/flag/AR.png
    - assets/flag/AS.png
    - assets/flag/AT.png
    - assets/flag/AU.png
    - assets/flag/AW.png
    - assets/flag/AX.png
    - assets/flag/AZ.png
    - assets/flag/BA.png
    - assets/flag/BB.png
    - assets/flag/BD.png
    - assets/flag/BE.png
    - assets/flag/BF.png
    - assets/flag/BG.png
    - assets/flag/BH.png
    - assets/flag/BI.png
    - assets/flag/BJ.png
    - assets/flag/BL.png
    - assets/flag/BM.png
    - assets/flag/BN.png
    - assets/flag/BO.png
    - assets/flag/BQ.png
    - assets/flag/BR.png
    - assets/flag/BS.png
    - assets/flag/BT.png
    - assets/flag/BV.png
    - assets/flag/BW.png
    - assets/flag/BY.png
    - assets/flag/BZ.png
    - assets/flag/CA.png
    - assets/flag/CC.png
    - assets/flag/CD.png
    - assets/flag/CF.png
    - assets/flag/CG.png
    - assets/flag/CH.png
    - assets/flag/CI.png
    - assets/flag/CK.png
    - assets/flag/CL.png
    - assets/flag/CM.png
    - assets/flag/CN.png
    - assets/flag/CO.png
    - assets/flag/CR.png
    - assets/flag/CU.png
    - assets/flag/CV.png
    - assets/flag/CW.png
    - assets/flag/CX.png
    - assets/flag/CY.png
    - assets/flag/CZ.png
    - assets/flag/DE.png
    - assets/flag/DJ.png
    - assets/flag/DK.png
    - assets/flag/DM.png
    - assets/flag/DO.png
    - assets/flag/DZ.png
    - assets/flag/EC.png
    - assets/flag/EE.png
    - assets/flag/EG.png
    - assets/flag/EH.png
    - assets/flag/ER.png
    - assets/flag/ES.png
    - assets/flag/ET.png
    - assets/flag/FI.png
    - assets/flag/FJ.png
    - assets/flag/FK.png
    - assets/flag/FM.png
    - assets/flag/FO.png
    - assets/flag/FR.png
    - assets/flag/GA.png
    - assets/flag/GB.png
    - assets/flag/GB-1.png
    - assets/flag/GD.png
    - assets/flag/GE.png
    - assets/flag/GF.png
    - assets/flag/GG.png
    - assets/flag/GH.png
    - assets/flag/GI.png
    - assets/flag/GL.png
    - assets/flag/GM.png
    - assets/flag/GN.png
    - assets/flag/GP.png
    - assets/flag/GQ.png
    - assets/flag/GR.png
    - assets/flag/GS.png
    - assets/flag/GT.png
    - assets/flag/GU.png
    - assets/flag/GW.png
    - assets/flag/GY.png
    - assets/flag/HK.png
    - assets/flag/HM.png
    - assets/flag/HN.png
    - assets/flag/HR.png
    - assets/flag/HT.png
    - assets/flag/HU.png
    - assets/flag/ID.png
    - assets/flag/IE.png
    - assets/flag/IM.png
    - assets/flag/IN.png
    - assets/flag/IO.png
    - assets/flag/IQ.png
    - assets/flag/IR.png
    - assets/flag/IS.png
    - assets/flag/IT.png
    - assets/flag/JE.png
    - assets/flag/JM.png
    - assets/flag/JO.png
    - assets/flag/JP.png
    - assets/flag/KE.png
    - assets/flag/KG.png
    - assets/flag/KH.png
    - assets/flag/KI.png
    - assets/flag/KM.png
    - assets/flag/KN.png
    - assets/flag/KP.png
    - assets/flag/KR.png
    - assets/flag/KW.png
    - assets/flag/KY.png
    - assets/flag/KZ.png
    - assets/flag/LA.png
    - assets/flag/LB.png
    - assets/flag/LC.png
    - assets/flag/LI.png
    - assets/flag/LK.png
    - assets/flag/LR.png
    - assets/flag/LS.png
    - assets/flag/LT.png
    - assets/flag/LU.png
    - assets/flag/LV.png
    - assets/flag/LY.png
    - assets/flag/MA.png
    - assets/flag/MC.png
    - assets/flag/MD.png
    - assets/flag/ME.png
    - assets/flag/MF.png
    - assets/flag/MG.png
    - assets/flag/MH.png
    - assets/flag/MK.png
    - assets/flag/ML.png
    - assets/flag/MM.png
    - assets/flag/MN.png
    - assets/flag/MO.png
    - assets/flag/MP.png
    - assets/flag/MQ.png
    - assets/flag/MQ-1.png
    - assets/flag/MR.png
    - assets/flag/MS.png
    - assets/flag/MT.png
    - assets/flag/MU.png
    - assets/flag/MV.png
    - assets/flag/MW.png
    - assets/flag/MX.png
    - assets/flag/MY.png
    - assets/flag/MZ.png
    - assets/flag/NA.png
    - assets/flag/NC.png
    - assets/flag/NE.png
    - assets/flag/NF.png
    - assets/flag/NG.png
    - assets/flag/NI.png
    - assets/flag/NL.png
    - assets/flag/NO.png
    - assets/flag/NP.png
    - assets/flag/NR.png
    - assets/flag/NU.png
    - assets/flag/NZ.png
    - assets/flag/OM.png
    - assets/flag/PA.png
    - assets/flag/PE.png
    - assets/flag/PF.png
    - assets/flag/PG.png
    - assets/flag/PH.png
    - assets/flag/PK.png
    - assets/flag/PL.png
    - assets/flag/PM.png
    - assets/flag/PN.png
    - assets/flag/PR.png
    - assets/flag/PS.png
    - assets/flag/PT.png
    - assets/flag/PW.png
    - assets/flag/PY.png
    - assets/flag/QA.png
    - assets/flag/RE.png
    - assets/flag/RO.png
    - assets/flag/RS.png
    - assets/flag/RU.png
    - assets/flag/RW.png
    - assets/flag/SA.png
    - assets/flag/SB.png
    - assets/flag/SC.png
    - assets/flag/SD.png
    - assets/flag/SE.png
    - assets/flag/SG.png
    - assets/flag/SH.png
    - assets/flag/SI.png
    - assets/flag/SJ.png
    - assets/flag/SK.png
    - assets/flag/SL.png
    - assets/flag/SM.png
    - assets/flag/SN.png
    - assets/flag/SO.png
    - assets/flag/SR.png
    - assets/flag/SS.png
    - assets/flag/ST.png
    - assets/flag/SV.png
    - assets/flag/SX.png
    - assets/flag/SY.png
    - assets/flag/SZ.png
    - assets/flag/TC.png
    - assets/flag/TD.png
    - assets/flag/TF.png
    - assets/flag/TG.png
    - assets/flag/TH.png
    - assets/flag/TJ.png
    - assets/flag/TK.png
    - assets/flag/TL.png
    - assets/flag/TM.png
    - assets/flag/TN.png
    - assets/flag/TO.png
    - assets/flag/TR.png
    - assets/flag/TT.png
    - assets/flag/TV.png
    - assets/flag/TW.png
    - assets/flag/TZ.png
    - assets/flag/UA.png
    - assets/flag/UG.png
    - assets/flag/UM.png
    - assets/flag/US.png
    - assets/flag/UY.png
    - assets/flag/UZ.png
    - assets/flag/VA.png
    - assets/flag/VC.png
    - assets/flag/VE.png
    - assets/flag/VG.png
    - assets/flag/VI.png
    - assets/flag/VN.png
    - assets/flag/VU.png
    - assets/flag/WF.png
    - assets/flag/WS.png
    - assets/flag/YE.png
    - assets/flag/YT.png
    - assets/flag/ZA.png
    - assets/flag/ZM.png
    - assets/flag/ZW.png